var fs = require('fs')
var file = (process.argv[2])
var buffer = fs.readFileSync(file)
var str =  buffer.toString()
var array = Number(str.split("\n"))
var lines = Number(array.length - 1)
console.log(lines)
